name: plunes
description: A new Flutter application.

version: 1.2.44+84
#version: 1.2.40+80 -- released on 26-mar
#version: 1.2.35+77--on23-mar
# ios build pushed 2.0.5(105) on 7-apr
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_countdown_timer: ^4.1.0 #21-mar-2023
#  cupertino_icons: ^1.0.5
  confetti: any
  readmore: ^2.2.0
  page_view_indicators: ^2.0.0
  #  flutter_swipe_action_cell: ^3.0.4
  #  simple_url_preview: any
  youtube_player_flutter: ^8.0.0
  #  intro_slider: ^1.2.0-----------------------------------
  intro_slider: ^4.2.0
  shared_preferences: ^2.0.12
  #  http: ^0.12.0+2----------------------------
  http: ^0.13.4
  #  modal_progress_hud: ^0.1.3
  date_format: ^2.0.5
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  image_picker: ^0.8.6+1
  pinput: ^2.0.0
  percent_indicator: ^4.0.0
  #  flutter_webview_plugin: ^0.3.8-----------------------------zzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  #  flutter_webview_plugin: ^0.4.0
  #  url_launcher: ^5.0.3
  url_launcher: ^6.0.18
  #  highlighter_coachmark: ^0.0.3
  transparent_image: ^2.0.0
  #  zoomable_image: ^1.3.1
  shimmer: ^2.0.0
  image_cropper: ^3.0.1
  #  progress_hud_v2: ^2.0.0
  pull_to_refresh: ^2.0.0
  web_socket_channel: ^2.1.0
  super_tooltip: ^1.0.1
  #  encrypt: ^2.2.0-------------------------------------
  encrypt: ^5.0.1
  #  device_info: ^0.2.1---------------------------------
  device_info_plus: ^4.0.0
  flutter_screenutil: ^5.1.1
  #  location_permissions: ^2.0.0-------------------------------
  permission_handler: ^10.2.0
  location: ^4.3.0
  #  geocoder: ^0.2.1--------------------------------
  geocoding: ^2.0.2
  #  google_maps_flutter: ^0.5.21+7------------------
#  google_maps_flutter: ^2.1.1 - on 31 mar
  google_maps_flutter: ^2.2.0
  #  flutter_google_places: 0.2.3-----------------------------
  flutter_google_places: 0.3.0
  #  firebase_core: ^0.5.0
  firebase_core: ^2.5.0
  #  firebase_analytics: ^6.0.0
  firebase_analytics: ^10.1.1
  firebase_remote_config: ^3.0.10
  firebase_crashlytics: ^3.0.12
  #  firebase_messaging: ^6.0.16-------------------------------
  firebase_messaging: ^14.2.2
  connectivity_plus: ^2.3.6
  #  fluttertoast: ^3.1.0--------------------------------
  #  fluttertoast: ^8.0.9
  toast: ^0.3.0
  #  file_picker: ^1.3.5---------------------------------
  file_picker: ^5.2.0
  #  file_picker: ^4.3.0
  #  open_file: ^3.0.3----------------------------------
  #  open_file: ^3.2.1
  path: ^1.8.1
  flutter_spinkit: ^5.1.0
  #  dropdownfield: ^0.0.2
  #  path_provider: ^1.1.0-------------------------------
  path_provider: ^2.0.8
  #  bottom_navigation_badge: ^1.0.3
  flutter_typeahead: ^4.1.0
  #  flutter_local_notifications: ^1.4.4+1------------------------------------
  #  flutter_local_notifications: ^12.0.4
  flutter_local_notifications: ^12.0.4
  share_plus: ^4.0.0
  #  share_plus: ^3.0.5
  #  dio: ^3.0.10--------------------------------------
  dio: ^5.0.0
  event_bus: ^2.0.0
  #  cached_network_image: ^2.0.0---------------------------
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  step_progress_indicator: ^1.0.2
  flutter_holo_date_picker: ^1.0.1+2
  #  webview_flutter: ^0.3.21
  webview_flutter: ^4.0.2
  flutter_datetime_picker: ^1.5.1
  scrollable_positioned_list: ^0.3.5
  package_info_plus: ^1.3.0
  #  facebook_app_events: ^0.7.1----------------------------
  facebook_app_events: ^0.18.3
  showcaseview: ^2.0.0+1
  #  sms_otp_auto_verify: ^1.2.2-----------------------------------
  sms_otp_auto_verify: ^2.1.0
  sms_autofill: ^2.2.0
  visibility_detector: ^0.3.3
  #  searchable_dropdown: ^1.1.3-------------------------
  #  adhara_socket_io: ^0.4.2+1
  socket_io_client: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.50
  flutter_charts: ^0.5.0
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.1.0
  dots_indicator: ^2.1.0
  #  flutter_windowmanager: ^0.0.2------------------------------
  flutter_windowmanager: ^0.2.0
  #  upi_pay: ^0.2.4-----------------------------------zzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  #  upi_pay: ^1.0.1
#  razorpay_flutter: ^1.3.4 #added on 22-mar-23
  bubble_tab_indicator: ^0.1.6
  dotted_line: ^3.1.0
  #  video_compress: ^3.1.1
  video_player: ^2.5.1
  flutter_bloc: ^8.1.2
  geolocator: ^9.0.1
  #  rxdart:
  rxdart: ^0.26.0
  stream: ^3.0.3
#  geocoder_location: ^0.1.1
  google_nav_bar: ^5.0.6
  #whatsapp login
  otpless_flutter: ^1.0.8
  #google fonts
  google_fonts: ^2.3.0

#  permission:
#    git:
#      url: https://github.com/plunes/permission.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/new_ios_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
      #  - asset: fonts/Raleway-Italic.ttf
      #    style: italic

  uses-material-design: true

  assets:
      - assets/images/
      - assets/ic_launcher_logo.png
      - assets/send.png
      - assets/gif/loading.gif
      - assets/send_active.png
      - assets/fb.png
      - assets/google.png
      - assets/city_icon.png
      - assets/test.png
      - assets/map_icon.png
      - assets/bid.png
      - assets/booking.png
      - assets/tick.png
      - assets/concern.png
      - assets/key.png
      - assets/account.png
      - assets/security.png
      - assets/all_payments.png
      - assets/payments2.png
      - assets/notification.png
      - assets/edit_profile.png
      - assets/change_pass.png
      - assets/logout.png
      - assets/logout2.png
      - assets/error_page.png
      - assets/images/enquiry/toggle_off.png
      - assets/images/enquiry/toggle_on.png
      - assets/new_home_banner.jpg
      - assets/images/nearyou/Dentist.png
      - assets/images/nearyou/Dermatology.png
      - assets/images/nearyou/Gynecology.png
      - assets/images/nearyou/Opthemalogist.png
      - assets/images/nearyou/Orthopedic.png
      - assets/images/nearyou/Pathology.png
      - assets/images/nearyou/Physiotherapy.png
      - assets/images/nearyou/Physotherepy.png
      - assets/images/nearyou/Radiology.png

      - assets/new_ios_icon.png
      - assets/plunes.png
      - assets/payments.png
      - assets/info.png
      - assets/heart.png
      - assets/consult.png
      - assets/doctor.png
      - assets/lawyer2.png
      - assets/soon.png
      - assets/no_img.png
      - assets/default_img.png
      - assets/prize.png
      - assets/bids.png
      - assets/consults.png
      - assets/searching.png
      - assets/logo1.png
      - assets/clock.png
      - assets/arrow.png
      - assets/payment_transfer.png
      - assets/utility.png
      - assets/images/bid/near_you.png
      - assets/images/login/first_user.png
      - assets/images/login/login_logo.png
      - assets/images/plusIcon.png
      - assets/images/CardExpired.png


      - assets/images/bottom_tabs/bid_active.png
      - assets/images/bottom_tabs/bid.png
      - assets/images/bottom_tabs/notification_active.png
      - assets/images/bottom_tabs/notification.png
      - assets/images/bottom_tabs/profile-active.png
      - assets/images/bottom_tabs/profile.png
      - assets/images/bottom_tabs/search_active.png
      - assets/images/bottom_tabs/search.png
      - assets/images/bottom_tabs/solution-active.png
      - assets/images/bottom_tabs/solution.png
      - assets/images/bottom_tabs/homeActive.png
      - assets/images/bottom_tabs/homeNonActive.png
      - assets/images/catalogue/catalog.png
      - assets/images/catalogue/edit.png
      - assets/images/catalogue/uploadPlus.png
      - assets/images/catalogue/view-sample.png
      - assets/images/bottom_tabs/notification_active-icon.png
      - assets/images/bottom_tabs/notification_inactive-icon.png
      - assets/images/bottom_tabs/cartSelectedImage.png
      - assets/images/bottom_tabs/cartUnSelectedImage.png
      - assets/images/bottom_tabs/previousActivitySelectedIcon.png
      - assets/images/bottom_tabs/previousActivityUnselectedIcon.png

      - assets/images/sliders/bidding.png
      - assets/images/sliders/search.png
      - assets/images/sliders/solution.png
      - assets/images/sliders/Procedures.png
      - assets/images/splash_final.jpg
      - assets/images/crossIcon.png
      - assets/images/whiteImage.png

      - assets/images/plockr_selected.png
      - assets/images/plockr_unselected.png
      - assets/images/uploadIcon.png
      - assets/images/lock.png
      - assets/images/pdf_icon.png
      - assets/images/pdf.png
      - assets/images/doc.png
      - assets/images/update.png
      - assets/images/serviceNotAvail.png

      - assets/images/achievments/gradient/1.jpg
      - assets/images/achievments/gradient/2.jpg
      - assets/images/achievments/gradient/3.jpg
      - assets/images/achievments/gradient/4.jpg
      - assets/images/achievments/gradient/5.jpg
      - assets/images/achievments/gradient/6.jpg
      - assets/images/achievments/gradient/8.jpg
      - assets/images/achievments/gradient/9.jpg
      - assets/images/achievments/gradient/10.jpg
      - assets/images/achievments/gradient/11.jpg
      - assets/images/achievments/achivement.png
      - assets/images/achievments/delete.png

      - assets/images/nav/about.png
      - assets/images/nav/logout.png
      - assets/images/nav/settings.png
      - assets/images/nav/appintment.png
      - assets/images/nav/availability.png
      - assets/images/nav/help.png
      - assets/images/nav/payments.png
      - assets/images/nav/availIcon.png
      - assets/images/nav/walletIcon.png



      - assets/images/profile/college.png
      - assets/images/profile/education.png
      - assets/images/profile/expertise.png
      - assets/images/profile/location.png
      - assets/images/profile/star_1.png
      - assets/images/profile/arrow.png
      - assets/images/profile/add_utility.png
      - assets/images/profile/practise.png
      - assets/images/profile/qualification.png
      - assets/images/profile/priceHighIcon.png
      - assets/images/profile/MapDark.png
      - assets/images/profile/MapIcon.png
      - assets/images/profile/ServiceNot.png
      - assets/images/profile/calIcon.png
      - assets/images/profile/eduIcon.png
      - assets/images/profile/emailIcon.png
      - assets/images/profile/phoneIcon.png
      - assets/images/profile/uniIcon.png
      - assets/images/profile/pathIcon.png
      - assets/images/profile/genderIcon.png
      - assets/images/profile/No_service.png
      - assets/images/profile/Introduction.png
      - assets/images/profile/Map.png
      - assets/images/profile/achievement.png
      - assets/images/profile/review.png
      - assets/images/profile/expert.png
      - assets/images/profile/specialization.png
      - assets/images/profile/greenCheck.png
      - assets/images/profile/defaulHosIcon.png

      - assets/images/bid/location.png
      - assets/images/bid/add_image.png
      - assets/images/bid/cancel.png
      - assets/images/bid/bid_active.png
      - assets/images/bid/failed.png
      - assets/images/bid/check.png
      - assets/images/bid/map.png
      - assets/images/bid/uncheck.png
      - assets/images/bid/tip.png
      - assets/images/solution/comment.png
      - assets/images/bottom_tabs/itemInCartImage.png

      - assets/images/help/booking-appointment.png
      - assets/images/help/hospHelp.png
      - assets/images/help/feedback.png
      - assets/images/help/online_solution.png
      - assets/images/help/other.png
      - assets/images/help/complain.png
      - assets/images/help/Thank you.png
      - assets/images/phonegrey.png
      - assets/images/tellIcongrey2.png
      - assets/images/walletgrey.png
      - assets/images/catIcon1.png
      - assets/images/calandergrey.png
      - assets/images/coupons.png
      - assets/images/credit.png
      - assets/images/refer.png
      - assets/images/cover.png
      - assets/images/user_landing_map.png
      - assets/images/locationIconUserLandingScreen.png
      - assets/images/arrow-down-Icon.png
      - assets/images/eye-with-a-diagonal-line3x.png
      - assets/images/search@3x.png
      - assets/images/cash.png
      - assets/images/drop-location-icon.png
      - assets/images/consultation-avatar.png
      - assets/images/procedure-avatar.png
      - assets/images/test-avatar.png
      - assets/images/Basic-icon.png
      - assets/images/cashIcon.png
      - assets/images/Profile_Inactive-Icon.png
      - assets/images/bulb-icon.png
      - assets/images/userprofileIcon.png
      - assets/images/no_appointment.png
      - assets/images/hospitalImage.png
      - assets/images/bookingLostEmoji.png
      - assets/images/solution/doctorMapImage.png
      - assets/images/solution/hospitalMapImage.png
      - assets/images/solution/homeCollectionImage.png
      - assets/images/solution/labMapImage.png
      - assets/images/bottom_tabs/unreadNotificationIcon.png
      - assets/images/setLocationFailImage.png
      - assets/images/setLocationMap.png
      - assets/images/refundImage.png
      - assets/images/couponImage.png
      - assets/images/bdSupportImage.png
      - assets/images/validForOneHourOnlyWatch.png
      - assets/images/refCodeUsedThrice.png
      - assets/images/plockrBgImage.png
      - assets/images/ratringStar.png
      - assets/images/reviewSubmitImage.png
      - assets/images/invoiceSuccessImage.png
      - assets/images/technologyBackground.png
      - assets/images/hosImage1XGreenBg.png
      - assets/images/hosImage2XGreenBg.png
      - assets/images/invalidSlotImage.png
      - assets/images/savedMoneyImage.png
      - assets/images/biddingAddedSuccessImage.png
      - assets/images/plunesPlaceHolderAndErrorLogo.png
      - assets/images/informativeIcon.png
      - assets/images/noActionableInsightIcon.png
      - assets/images/noRealTimeInsightIcon.png
      - assets/images/Refundable.png
      - assets/images/PrefferedTiming.png
      - assets/images/Lockin100.png
      - assets/images/MakePayement.png
      - assets/images/AutomatedAppointment.png
      - assets/images/NegotiateIRealtime.png
      - assets/images/RealTimeIns.png
      - assets/images/ActionableIns.png
      - assets/images/ExtensiveMarketing.png
      - assets/images/Patientfootfal.png
      - assets/images/BusinessPerformance.png
      - assets/images/CenterIntegration.png
      - assets/images/notification_empty_screen_icon.png
      - assets/images/enterTestAndProcedureDetailsImage.png
      - assets/images/testAndProcedureQuerySubmittedImage.png
      - assets/images/Common.png
      - assets/images/editPencilProfile.png
      - assets/images/doc_placeholder.png
      - assets/images/achievement_placeholder.png
      - assets/images/prev_missed_act_icon.png
      - assets/images/noSlotAvailableImage.png
      - assets/images/plunesCommonGreenBgImage.png
      - assets/images/happyEmoji.png
      - assets/images/turnOffNotification.png
      - assets/images/savePriceInCatalogueImage.png
      - assets/images/insight_bg_img.png
      - assets/images/bin.png
      - assets/images/blueBellIcon.png
      - assets/images/availability_edit_image.png
      - assets/images/certifiedImage.png
      - assets/images/solution/zeroCostEmiIcon.png
      - assets/images/solution/firstConslFree.png
      - assets/images/solution/freeTeleConsImg.png
      - assets/images/solution/paymentRefIcon.png
      - assets/images/solution/plunesVerifiedImg.png
      - assets/images/solution/prefTimeIcon.png
      - assets/images/bottom_tabs/exploreSelectedImage.png
      - assets/images/bottom_tabs/exploreUnSelectedImage.png
      - assets/images/pricesValidThroughAppIcon.png
      - assets/images/add_to_cart_success_image.png
      - assets/images/cartImage.png
      - assets/images/emptyCartItemsImage.png

      - assets/images/new_sol_img/cameraIcon.png
      - assets/images/new_sol_img/documentIcon.png
      - assets/images/new_sol_img/uploadVideoIcon.png
      - assets/images/unselectedFacilityIcon.png
      - assets/images/selectedfacilityIcon.png
      - assets/images/pauseVideoIcon.png
      - assets/images/add_special_offer_insight.png
      - assets/images/specialInsightOfferImage.png
      - assets/images/encryptionPopupImage.png
      - assets/gif/animation_500_klkj44md.gif
      - assets/images/whatsappIcon.png
      - assets/images/callingIconWhite.png
      - assets/gif/animation_500_kllw8ofi.gif
      - assets/images/home_screen_image.png
      - assets/images/profVerificationImage.png
      - assets/images/book_via_insurance_image.png
      - assets/images/bottom_tabs/activityUn.png
      - assets/images/bottom_tabs/activitySel.png

      - assets/videos/app_tour/2.mp4
      - assets/videos/app_tour/1.mp4
      - assets/videos/app_tour/3.mp4
      - assets/videos/app_tour/4.mp4

