name: plunes
description: A new Flutter application.

version: 1.2.32+73

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  confetti: any
  readmore: ^1.0.0
  page_view_indicators: ^1.3.1
  flutter_swipe_action_cell: ^1.0.5+1
  #  simple_url_preview: any
  youtube_player_flutter: ^7.0.0+7
  intro_slider: ^1.2.0
  shared_preferences: ^0.5.2
  http: ^0.12.0+2
  modal_progress_hud: ^0.1.3
  date_format: ^1.0.6
  date_picker_timeline: ^1.2.0
  intl: ^0.16.0
  image_picker: 0.6.7+21
  pinput: ^0.1.10
  percent_indicator: ^2.0.0
  flutter_webview_plugin: ^0.3.8
  url_launcher: ^5.0.3
  highlighter_coachmark: ^0.0.3
  transparent_image: ^0.1.0
  zoomable_image: ^1.3.1
  shimmer: ^1.0.0
  image_cropper: ^1.1.0
  progress_hud_v2: ^2.0.0
  pull_to_refresh: ^1.5.5
  web_socket_channel: ^1.0.15
  super_tooltip: ^0.9.0
  encrypt: ^2.2.0
  device_info: ^0.2.1
  flutter_screenutil: ^0.6.0
  location_permissions: ^2.0.0
  location: ^2.3.5
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.21+7
  flutter_google_places: 0.2.3
  firebase_messaging: ^6.0.16
  connectivity: ^0.4.3+5
  fluttertoast: ^3.1.0
  file_picker: ^1.3.5
  open_file: ^3.0.3
  path: ^1.6.2
  flutter_spinkit: ^4.0.0
  dropdownfield: ^0.0.2
  path_provider: ^1.1.0
  bottom_navigation_badge: ^1.0.3
  flutter_typeahead: ^1.6.1
  flutter_local_notifications: ^1.4.4+1
  share: ^0.6.3+1
  dio: ^3.0.10
  event_bus: ^1.1.1
  cached_network_image: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  step_progress_indicator: ^0.2.4+7
  rxdart:
  flutter_holo_date_picker: ^0.1.3+3s
  webview_flutter: ^0.3.21
  flutter_datetime_picker: ^1.4.0
  firebase_crashlytics: ^0.1.3+3
  scrollable_positioned_list: ^0.1.6
  package_info: ^0.4.1
  firebase_remote_config: ^0.3.1+1
  facebook_app_events: ^0.6.0
  showcaseview: ^0.1.5
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  sms_otp_auto_verify: ^1.2.2
  visibility_detector: ^0.1.5
  searchable_dropdown: ^1.1.3
  adhara_socket_io: ^0.4.2+1
  socket_io_client: ^0.9.11
  syncfusion_flutter_gauges: ^18.3.38
  charts_flutter: ^0.9.0
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.3.1
  dots_indicator: ^1.2.0
  flutter_windowmanager: ^0.0.2
#  upi_pay: ^0.2.4
  bubble_tab_indicator: ^0.1.4
  dotted_line: ^2.0.2
  video_compress: ^2.1.0
  video_player: ^1.0.1
  permission:
    git:
      url: https://github.com/plunes/permission.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
      #  - asset: fonts/Raleway-Italic.ttf
      #    style: italic

  uses-material-design: true

  assets:
    - assets/send.png
    - assets/gif/loading.gif
    - assets/send_active.png
    - assets/fb.png
    - assets/google.png
    - assets/city_icon.png
    - assets/test.png
    - assets/map_icon.png
    - assets/bid.png
    - assets/booking.png
    - assets/tick.png
    - assets/concern.png
    - assets/key.png
    - assets/account.png
    - assets/security.png
    - assets/all_payments.png
    - assets/payments2.png
    - assets/notification.png
    - assets/edit_profile.png
    - assets/change_pass.png
    - assets/logout.png
    - assets/logout2.png
    - assets/error_page.png
    - assets/images/enquiry/toggle_off.png
    - assets/images/enquiry/toggle_on.png

    - assets/images/nearyou/Dentist.png
    - assets/images/nearyou/Dermatology.png
    - assets/images/nearyou/Gynecology.png
    - assets/images/nearyou/Opthemalogist.png
    - assets/images/nearyou/Orthopedic.png
    - assets/images/nearyou/Pathology.png
    - assets/images/nearyou/Physiotherapy.png
    - assets/images/nearyou/Physotherepy.png
    - assets/images/nearyou/Radiology.png

    - assets/payments.png
    - assets/info.png
    - assets/heart.png
    - assets/consult.png
    - assets/doctor.png
    - assets/lawyer2.png
    - assets/soon.png
    - assets/no_img.png
    - assets/default_img.png
    - assets/prize.png
    - assets/bids.png
    - assets/consults.png
    - assets/searching.png
    - assets/logo1.png
    - assets/clock.png
    - assets/arrow.png
    - assets/payment_transfer.png
    - assets/utility.png
    - assets/images/bid/near_you.png
    - assets/images/login/first_user.png
    - assets/images/login/login_logo.png
    - assets/images/plusIcon.png
    - assets/images/CardExpired.png


    - assets/images/bottom_tabs/bid_active.png
    - assets/images/bottom_tabs/bid.png
    - assets/images/bottom_tabs/notification_active.png
    - assets/images/bottom_tabs/notification.png
    - assets/images/bottom_tabs/profile-active.png
    - assets/images/bottom_tabs/profile.png
    - assets/images/bottom_tabs/search_active.png
    - assets/images/bottom_tabs/search.png
    - assets/images/bottom_tabs/solution-active.png
    - assets/images/bottom_tabs/solution.png
    - assets/images/bottom_tabs/homeActive.png
    - assets/images/bottom_tabs/homeNonActive.png
    - assets/images/catalogue/catalog.png
    - assets/images/catalogue/edit.png
    - assets/images/catalogue/uploadPlus.png
    - assets/images/catalogue/view-sample.png
    - assets/images/bottom_tabs/notification_active-icon.png
    - assets/images/bottom_tabs/notification_inactive-icon.png
    - assets/images/bottom_tabs/cartSelectedImage.png
    - assets/images/bottom_tabs/cartUnSelectedImage.png
    - assets/images/bottom_tabs/previousActivitySelectedIcon.png
    - assets/images/bottom_tabs/previousActivityUnselectedIcon.png

    - assets/images/sliders/bidding.png
    - assets/images/sliders/search.png
    - assets/images/sliders/solution.png
    - assets/images/sliders/Procedures.png
    - assets/images/splash_final.jpg
    - assets/images/crossIcon.png
    - assets/images/whiteImage.png

    - assets/images/plockr_selected.png
    - assets/images/plockr_unselected.png
    - assets/images/uploadIcon.png
    - assets/images/lock.png
    - assets/images/pdf_icon.png
    - assets/images/pdf.png
    - assets/images/doc.png
    - assets/images/update.png
    - assets/images/serviceNotAvail.png

    - assets/images/achievments/gradient/1.jpg
    - assets/images/achievments/gradient/2.jpg
    - assets/images/achievments/gradient/3.jpg
    - assets/images/achievments/gradient/4.jpg
    - assets/images/achievments/gradient/5.jpg
    - assets/images/achievments/gradient/6.jpg
    - assets/images/achievments/gradient/8.jpg
    - assets/images/achievments/gradient/9.jpg
    - assets/images/achievments/gradient/10.jpg
    - assets/images/achievments/gradient/11.jpg
    - assets/images/achievments/achivement.png
    - assets/images/achievments/delete.png

    - assets/images/nav/about.png
    - assets/images/nav/logout.png
    - assets/images/nav/settings.png
    - assets/images/nav/appintment.png
    - assets/images/nav/availability.png
    - assets/images/nav/help.png
    - assets/images/nav/payments.png
    - assets/images/nav/availIcon.png
    - assets/images/nav/walletIcon.png



    - assets/images/profile/college.png
    - assets/images/profile/education.png
    - assets/images/profile/expertise.png
    - assets/images/profile/location.png
    - assets/images/profile/star_1.png
    - assets/images/profile/arrow.png
    - assets/images/profile/add_utility.png
    - assets/images/profile/practise.png
    - assets/images/profile/qualification.png
    - assets/images/profile/priceHighIcon.png
    - assets/images/profile/MapDark.png
    - assets/images/profile/MapIcon.png
    - assets/images/profile/ServiceNot.png
    - assets/images/profile/calIcon.png
    - assets/images/profile/eduIcon.png
    - assets/images/profile/emailIcon.png
    - assets/images/profile/phoneIcon.png
    - assets/images/profile/uniIcon.png
    - assets/images/profile/pathIcon.png
    - assets/images/profile/genderIcon.png
    - assets/images/profile/No_service.png
    - assets/images/profile/Introduction.png
    - assets/images/profile/Map.png
    - assets/images/profile/achievement.png
    - assets/images/profile/review.png
    - assets/images/profile/expert.png
    - assets/images/profile/specialization.png
    - assets/images/profile/greenCheck.png
    - assets/images/profile/defaulHosIcon.png

    - assets/images/bid/location.png
    - assets/images/bid/add_image.png
    - assets/images/bid/cancel.png
    - assets/images/bid/bid_active.png
    - assets/images/bid/failed.png
    - assets/images/bid/check.png
    - assets/images/bid/map.png
    - assets/images/bid/uncheck.png
    - assets/images/bid/tip.png
    - assets/images/solution/comment.png
    - assets/images/bottom_tabs/itemInCartImage.png

    - assets/images/help/booking-appointment.png
    - assets/images/help/hospHelp.png
    - assets/images/help/feedback.png
    - assets/images/help/online_solution.png
    - assets/images/help/other.png
    - assets/images/help/complain.png
    - assets/images/help/Thank you.png
    - assets/images/phonegrey.png
    - assets/images/tellIcongrey2.png
    - assets/images/walletgrey.png
    - assets/images/catIcon1.png
    - assets/images/calandergrey.png
    - assets/images/coupons.png
    - assets/images/credit.png
    - assets/images/refer.png
    - assets/images/cover.png
    - assets/images/user_landing_map.png
    - assets/images/locationIconUserLandingScreen.png
    - assets/images/arrow-down-Icon.png
    - assets/images/eye-with-a-diagonal-line3x.png
    - assets/images/search@3x.png
    - assets/images/cash.png
    - assets/images/drop-location-icon.png
    - assets/images/consultation-avatar.png
    - assets/images/procedure-avatar.png
    - assets/images/test-avatar.png
    - assets/images/Basic-icon.png
    - assets/images/cashIcon.png
    - assets/images/Profile_Inactive-Icon.png
    - assets/images/bulb-icon.png
    - assets/images/userprofileIcon.png
    - assets/images/no_appointment.png
    - assets/images/hospitalImage.png
    - assets/images/bookingLostEmoji.png
    - assets/images/solution/doctorMapImage.png
    - assets/images/solution/hospitalMapImage.png
    - assets/images/solution/homeCollectionImage.png
    - assets/images/solution/labMapImage.png
    - assets/images/bottom_tabs/unreadNotificationIcon.png
    - assets/images/setLocationFailImage.png
    - assets/images/setLocationMap.png
    - assets/images/refundImage.png
    - assets/images/couponImage.png
    - assets/images/bdSupportImage.png
    - assets/images/validForOneHourOnlyWatch.png
    - assets/images/refCodeUsedThrice.png
    - assets/images/plockrBgImage.png
    - assets/images/ratringStar.png
    - assets/images/reviewSubmitImage.png
    - assets/images/invoiceSuccessImage.png
    - assets/images/technologyBackground.png
    - assets/images/hosImage1XGreenBg.png
    - assets/images/hosImage2XGreenBg.png
    - assets/images/invalidSlotImage.png
    - assets/images/savedMoneyImage.png
    - assets/images/biddingAddedSuccessImage.png
    - assets/images/plunesPlaceHolderAndErrorLogo.png
    - assets/images/informativeIcon.png
    - assets/images/noActionableInsightIcon.png
    - assets/images/noRealTimeInsightIcon.png
    - assets/images/Refundable.png
    - assets/images/PrefferedTiming.png
    - assets/images/Lockin100.png
    - assets/images/MakePayement.png
    - assets/images/AutomatedAppointment.png
    - assets/images/NegotiateIRealtime.png
    - assets/images/RealTimeIns.png
    - assets/images/ActionableIns.png
    - assets/images/ExtensiveMarketing.png
    - assets/images/Patientfootfal.png
    - assets/images/BusinessPerformance.png
    - assets/images/CenterIntegration.png
    - assets/images/notification_empty_screen_icon.png
    - assets/images/enterTestAndProcedureDetailsImage.png
    - assets/images/testAndProcedureQuerySubmittedImage.png
    - assets/images/Common.png
    - assets/images/editPencilProfile.png
    - assets/images/doc_placeholder.png
    - assets/images/achievement_placeholder.png
    - assets/images/prev_missed_act_icon.png
    - assets/images/noSlotAvailableImage.png
    - assets/images/plunesCommonGreenBgImage.png
    - assets/images/happyEmoji.png
    - assets/images/turnOffNotification.png
    - assets/images/savePriceInCatalogueImage.png
    - assets/images/insight_bg_img.png
    - assets/images/bin.png
    - assets/images/blueBellIcon.png
    - assets/images/availability_edit_image.png
    - assets/images/certifiedImage.png
    - assets/images/solution/zeroCostEmiIcon.png
    - assets/images/solution/firstConslFree.png
    - assets/images/solution/freeTeleConsImg.png
    - assets/images/solution/paymentRefIcon.png
    - assets/images/solution/plunesVerifiedImg.png
    - assets/images/solution/prefTimeIcon.png
    - assets/images/bottom_tabs/exploreSelectedImage.png
    - assets/images/bottom_tabs/exploreUnSelectedImage.png
    - assets/images/pricesValidThroughAppIcon.png
    - assets/images/add_to_cart_success_image.png
    - assets/images/cartImage.png
    - assets/images/emptyCartItemsImage.png

    - assets/images/new_sol_img/cameraIcon.png
    - assets/images/new_sol_img/documentIcon.png
    - assets/images/new_sol_img/uploadVideoIcon.png
    - assets/images/unselectedFacilityIcon.png
    - assets/images/selectedfacilityIcon.png
    - assets/images/pauseVideoIcon.png
    - assets/images/add_special_offer_insight.png
    - assets/images/specialInsightOfferImage.png
    - assets/images/encryptionPopupImage.png



#permission:
#  git:
#  url: https://github.com/kamlesh9070/permission
