#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/gautamsinghmaurya/flutter_path/actual_path"
export "FLUTTER_APPLICATION_PATH=/Users/gautamsinghmaurya/Freelance/plunes_project/Code/plunes_flutter_bloc"
export "FLUTTER_TARGET=/Users/gautamsinghmaurya/Freelance/plunes_project/Code/plunes_flutter_bloc/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/gautamsinghmaurya/flutter_path/actual_path/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.2.34"
export "FLUTTER_BUILD_NUMBER=75"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
